# yml file for CIs using https://github.com/xu-cheng/latex-action
name: compile
on: [push]

jobs:
  compilation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tex/libroResMat2.tex
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: tex/libroResMat2.pdf
#      - name: Download a Build Artifact
#        uses: actions/download-artifact@v3
#        with: 
#          name: PDF 
#      - name: Display structure of downloaded files
#        run: ls -R
